src/Entity/Ad.php
<?php

namespace App\Entity;

use App\Entity\User;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;


/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *  fields={"title"},
 *  message="Une autre annonce possède déjà, merci de le modifier"
 *  )
 * @Vich\Uploadable
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=3, max=255, minMessage="Le tritre doit faire au moins 3 caractères", maxMessage="Le titre doit faire maximum 255 caractères")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=10, minMessage="Votre introduction doit faire plus de 10 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=20, minMessage="Votre description ne peut pas faire moins de 20 caractères" )
     */
    private $content;

     /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="coverImage")
     * 
     * @var File|null
     */
    private $imageFile;

     /**
     * @ORM\Column(type="string")
     *
     * @var string|null
     */
    private $coverImage;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

     /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTimeInterface|null
     */
    private $updatedAt;

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

      /**
     * Callback appelé à chaque fois qu'on créé une réservation
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */
    public function prePersist() {
        if(empty($this->updatedAt)) {
            $this->updatedAt = new \DateTime();
        }
    }

    /**
     * Si vous téléchargez manuellement un fichier (c'est-à-dire si vous n'utilisez pas Symfony Form), assurez-vous qu'une instance
     * de 'UploadedFile' est injecté dans ce setter pour déclencher la mise à jour. Si ce
     * le paramètre de configuration du bundle 'inject_on_load' est défini sur 'true' ce setter
     * doit pouvoir accepter une instance de 'File' car le bundle en injectera une ici
     * pendant l'hydratation Doctrine.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    /**
     * @return null|File
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }


    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Permet d'initialiser le slug ! 
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function initializeSlug() {
        if(empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }


     /**
     * Permet de récupérer le commentaire d'un auteur par rapport à une annonce
     *
     * @param User $author
     * @return Comment|null
     */
    public function getCommentFromAuthor(User $author){
        foreach($this->comments as $comment) {
            if($comment->getAuthor() === $author) return $comment;
        }

        return null;
    }

    /**
     * Permet d'obtenir la moyenne globale des notes pour cette annonce
     *
     * @return float
     */
    public function getAvgRatings() {
        // Calculer la somme des notations
        $sum = array_reduce($this->comments->toArray(), function($total, $comment) {
            return $total + $comment->getRating();
        }, 0);

        // Faire la division pour avoir la moyenne
        if(count($this->comments) > 0) return $sum / count($this->comments);

        return 0;
    }


    /**
     * Permet d'obtenir un tableau des jours qui ne sont pas disponibles pour cette annonce
     *
     * @return array Un tableau d'objets DateTime représentant les jours d'occupation
     */
    public function getNotAvailableDays() {
        $notAvailableDays = [];

        foreach($this->bookings as $booking) {
            // Calculer les jours qui se trouvent entre la date d'arrivée et de départ
            $resultat = range(
                $booking->getStartDate()->getTimestamp(), 
                $booking->getEndDate()->getTimestamp(), 
                24 * 60 * 60
            );
            
            $days = array_map(function($dayTimestamp){
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            }, $resultat);

            $notAvailableDays = array_merge($notAvailableDays, $days);
        }

        return $notAvailableDays;
    }


    public function getId(): ?int
    {

        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

src/Controller/Front/AdController.php
<?php

namespace App\Controller\Front;

use App\Entity\Ad;
use App\Form\AdType;
use App\Entity\Contact;
use App\Form\ContactType;
use App\Repository\AdRepository;
use App\Service\PaginationService;
use App\Service\NotificationService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AdController extends AbstractController
{

    
    
    // les prestataires sans pagination
    //  /**
    //  * @Route("/ads", name="ads_index")
    //  */
    // public function index(AdRepository $repo)
    // {
    //     $ads = $repo->findAll();
    //     return $this->render('ad/index.html.twig', [
    //         'ads' => $ads
    //     ]);
    // }
    
    
    /**
     * @Route("/ads/{page<\d+>?1}", name="ads_index")
     *
     */
    public function index(AdRepository $repo, $page, PaginationService $pagination)
    {
        $em = $this->getDoctrine()->getRepository(Ad::class);
        $result = $em->findAll();
        if(isset($_POST['title'])) {

            $result=$em->search($_POST['title']);
        }

        $pagination->setEntityClass(Ad::class)
                   ->setPage($page)
                   ->setLimit(21);

        return $this->render('ad/index.html.twig', [
            'pagination' => $pagination,
            'result' => $result
        ]);
    }
    
   
    /**
     * Permet d'afficher une seule annonce
     *
     * @Route("/ads/{slug}", name="ads_show")
     * 
     * @return Response
     */
    public function show(Ad $ad,Request $request, NotificationService $notification){

        $contact = new Contact();
        $contact->setAd($ad);
        $form = $this->createForm(ContactType::class, $contact);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $notification->notify($contact);
            $this->addFlash('success', 'Votre demande a bien été envoyer');

        return $this->redirectToRoute('ads_show',
        ['slug' => $ad->getSlug()]);
        }
        return $this->render('/ad/show.html.twig',[
            'ad' => $ad,
            'contactForm' => $form->createView()
        ]);
    }

}

src/Controller/Presta/PrestaAdController.php
<?php

namespace App\Controller\Presta;

use App\Entity;
use App\Entity\Ad;
use App\Form\AdType;
use App\Entity\Contact;
use App\Form\ContactType;
use App\Repository\AdRepository;
use App\Service\PaginationService;
use App\Service\NotificationService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PrestaAdController extends AbstractController
{

    
    
    
    /**
     * Permet de créer une annonce
     * 
     * @Route("presta/ads/new", name="presta_ads_create")
     * @IsGranted("ROLE_PRESTA")
     * @return Response
     */
    public function create(Request $request, EntityManagerInterface $entityManager){

        $ad = new Ad;

        $form = $this->createForm(AdType::class, $ad);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            foreach($ad->getImages() as $image){
                $image->setAd($ad);
                $entityManager->persist($image);
            }

            $ad->setAuthor($this->getUser());

            $entityManager->persist($ad);
            $entityManager->flush();

            $this->addFlash(
                'success',
                "L'annonce <strong>{$ad->getTitle()}</strong> a bien été enregistrée !"
            );

            return $this->redirectToRoute('ads_show', [
                'slug' => $ad->getSlug()
            ]);
        }

        return $this->render('presta/ad/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * Permet d'afficher le formulaire d'édition
     *
     * @Route("presta/ads/{slug}/edit", name="presta_ads_edit")
     * 
     * @Security("is_granted('ROLE_PRESTA') and user === ad.getauthor()", message="Cette
     *  annonce ne vous appartient pas, vous ne pouvez pas la modifier")
     * 

     */
    public function edit(Ad $ad, Request $request, EntityManagerInterface $entityManager){

        $form = $this->createForm(AdType::class, $ad);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            foreach($ad->getImages() as $image){
                $image->setAd($ad);
                $entityManager->persist($image);
            }
            $entityManager->persist($ad);
            $entityManager->flush();

            $this->addFlash(
                'success',
                "Les modifications de l'annonce <strong>{$ad->getTitle()}</strong> a bien été enregistrée !"
            );

            return $this->redirectToRoute('presta_ads_show', [
                'slug' => $ad->getSlug()
            ]);
        }

        return $this->render('presta/ad/edit.html.twig', [
            'form' => $form->createView(),
            'ad' => $ad
        ]);

    }
    
    /**
     * Permet d'afficher une seule annonce
     *
     * @Route("presta/ads/{slug}", name="presta_ads_show")
     * 
     * @return Response
     */
    public function show(Ad $ad,Request $request, NotificationService $notification){

        $contact = new Contact();
        $contact->setAd($ad);
        $form = $this->createForm(ContactType::class, $contact);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $notification->notify($contact);
            $this->addFlash('success', 'Votre demande a bien été envoyer');

        return $this->redirectToRoute('ads_show',
        ['slug' => $ad->getSlug()]);
        }
        return $this->render('presta/ad/show.html.twig',[
            'ad' => $ad,
            'contactForm' => $form->createView()
        ]);
    }

    /**
     * Permet de supprimer une annonce
     *
     * @Route("presta/ads/{slug}/delete", name="presta_ads_delete")
     * 
     * @Security("is_granted('ROLE_PRESTA') and user == ad.getAuthor()", message="Vous n'avez pas le droit d'accéder à cette ressource")
     * 
     * @param Ad $ad
     * @param Request $request
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    public function delete(Ad $ad, Request $request, EntityManagerInterface $entityManager){
        $entityManager->remove($ad);
        $entityManager->flush();

        $this->addFlash(
            'success',
            "L'annonce <strong>{$ad->getTitle()}</strong> a bien été supprimée !"
        );

        return $this->redirectToRoute("presta_account_index");
    }

}

templates/presta/ad/_ad.html.twig
{%  set url = path('presta_ads_show', { 'slug': ad.slug }) %}

    <div class="col-md-4">
        <div class="card  mb-3" class="card1">
         {#   <div class="card-header text-center">
                {{ ad.rooms }} chambres, <strong>{{ad.price | number_format(2, ',', ' ')}} &euro; / nuit </strong> <br>
                
                {% if ad.comments|length > 0 %}
                {% include 'partials/rating.html.twig' with {'rating': ad.avgRatings} %}
                {% else %}
                    <small>Pas encore noté</small>
                {% endif %}
            </div>#}
            <a href="{{ url }}">
            {# avec vichuploader pour afficher src="{{ vich_uploader_asset(ad, 'imageFile')}}"#}
                <img src="{{ ad.coverImage }}" alt="Image de la prestation"
                style="height: 200px; width: 100%; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22318%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20318%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_158bd1d28ef%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A16pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_158bd1d28ef%22%3E%3Crect%20width%3D%22318%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22129.359375%22%20y%3D%2297.35%22%3EImage%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E">
            </a>
            <div class="card-body text-center">
                <h6 > <a class="card-subtitle mb-2 text-muted btn-link" href="{{ path('category_show', { 'slug': ad.category.slug }) }}">
                        {{ ad.category.title }} 
                    </a> <h6 class="card-title">
                  
                <h6 class="card-title">
                   <strong> <a href="{{ url }}" class="btn-link">
                        {{ ad.title }} 
                    </a> </strong> 
                <p class="mt-3">
                    {% if ad.comments|length > 0 %}
                {% include 'partials/rating.html.twig' with {'rating': ad.avgRatings} %} <span style="font-size: 16px; line-height: 21px; color: #8c8c8c">{{ ad.comments|length }}</span>
                {% else %}
                    <small>Pas encore noté</small>
                {% endif %}
                </p>
                </h6>
                <p class="card-text" id="description">
                    {{ ad.introduction|slice(0, 80) ~ '...'}}
                </p>
                <p class="row d-inline-flex">
                <a href="{{ url }}" class="btn btn-primary float-right btn-sm"> En savoir plus !</a>
                
                {% if app.user and app.user == ad.author %}
                    <a href="{{ path('presta_ads_edit', {'slug': ad.slug}) }}" class="btn btn-secondary btn-sm">Modifier la prestation</a>
                {% endif %}
                </p>
            </div>
        </div>
    </div>
    

templates/presta/ad/_collection.html.twig
{% block _ad_images_widget %}
    <p> Ici, vous pouvez ajouter vos propres images ! </p>

    {{ form_widget(form) }}

    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-dark"> 
            <i class="fas fa-plus"></i>
            Ajouter une image 
        </button>
    </div>
{% endblock %}

{% block _ad_images_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block _ad_images_entry_widget %}
    <div class="form-group" id="block_{{ id }}">
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{ form_widget(form.url) }}
                        {{ form_errors(form.url) }}
                    </div>
                    <div class="col">
                        {{ form_widget(form.caption) }}
                        {{ form_errors(form.caption) }}
                    </div>
                </div>
                <div class="col-2">
                    <button type="button" data-action="delete" data-target="#block_{{id}}" class="btn btn-danger">X</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/presta/ad/edit.html.twig
{% extends "presta/base.html.twig" %}  

{% block title %}
    Edition d'une prestation
{% endblock %}

{% form_theme form 'presta/ad/_collection.html.twig' %}

{% block body %}
    
    <div class="container">
        <h1> Modifier la prestation </h1>

        {{ form_start(form) }}

        {{ form_widget(form) }}

        <input type="hidden" id="widgets-counter" value="0">

        <button type="submit" class="btn btn-primary">Enregistrer les modifications</button>

        {{ form_end(form) }}
    </div>

{% endblock %}

{% block javascripts %}

<script src="{{ asset('build/js/ad.js') }}"></script>

{% endblock %}

templates/presta/ad/index.html.twig
{% extends 'presta/base.html.twig' %}

{% block title %}Nos magnifiques prestations{% endblock %}

{% block body %}

<div class="container">
    <h1 class="py-5 text-center"> Voici les annonces de nos prestataires !</h1>

    <div class="row">
        {% for ad in pagination.data %}
        
            {% include 'presta/ad/_ad.html.twig' %}
        
        {% endfor %}
        
    </div>
    {{ pagination.display() }}
</div>

{% endblock %}

templates/presta/ad/show.html.twig
{% extends "presta/base.html.twig" %}

{% block title %}
    {{ ad.title }}
{% endblock %}

{% block body %}
{% for message in app.flashes('success') %}
           <div class="alert alert-success">
                {{ message }}
           </div> 
    {% endfor %}

{% if not contactForm.vars.valid %}
    <div class="alert alert-danger">
            Veuillez correctement remplir le formulaire.
           </div> 
    {% endif %}

<div class="ad-title" style="background-image: url({{ ad.coverImage }})">  
    <div class="container ">
        <h1>{{ ad.title }} </h1>
        <p>  {{ad.introduction }}</p>
        {#<p class="h2">
            <strong>{{ ad.rooms }} chambres</strong> pour <strong> {{ad.price | number_format(2, ',', ' ')}} &euro;
            </strong> par nuit
        </p>#}
        <a href="{{   path('booking_create', {'slug' : ad.slug})  }}" class="btn btn-secondary">Réserver !</a>
        
        <a href="#" class="btn btn-secondary" id="contactButton" {% if contactForm.vars.submitted %} style="display: none;" {% endif %}> Contacter le prestataire </a>
           

        {% if app.user and app.user == ad.author %}
            <a href="{{ path('presta_ads_edit', {'slug': ad.slug}) }}" class="btn btn-secondary">Modifier l'annonce</a>
            <a href="{{ path('presta_ads_delete', {'slug': ad.slug}) }}" class="btn btn-danger" onclick="return confirm(
            `Êtes vous sur de vouloir supprimer la prestation : {{ad.title}} ?`)"> Supprimer l'annonce</a>
        {% endif %}
        </div>
</div>

<div class="container">
 <div id="contactForm" class="mt-4" {% if not  contactForm.vars.submitted %} style="display: none;" {% endif %} >
                {{ form_start(contactForm) }}
                <p class="font-weight-bold text-center">Formulaire de contact</p>
                <div class="row">
                    <div class="col"> 
                        <div class="md-form mt-0 input-with-post-icon">
                            <i class="fas fa-user input-prefix"></i>
                            {{ form_row(contactForm.firstname) }} 
                        </div>
                    </div>
                    <div class="col">
                        <div class="md-form mt-0 input-with-post-icon">
                            <i class="fas fa-user input-prefix"></i>
                            {{ form_row(contactForm.lastname) }} 
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="md-form mt-0 input-with-post-icon">
                            <i class="fas fa-phone input-prefix"></i>
                            {{ form_row(contactForm.phone) }} 
                        </div>
                    </div>
                    <div class="col">   
                        <div class="md-form mt-0 input-with-post-icon">
                            <i class="fas fa-envelope  input-prefix"></i>
                            {{ form_row(contactForm.email) }} 
                        </div>
                    </div>
                </div>
                    {{ form_rest(contactForm) }}
               
                <div class="form-group">
                    <button class="btn btn-primary"> Envoyer </button>
                </div>
                {{ form_end(contactForm) }}
            </div>
    <div class="row">
        <div class="col-md-8 mb-3">
        {{ ad.content | raw}}

            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    {% for image in ad.images %}
                        <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0 }}" {%  if loop.first %}class="active"{%   endif  %}></li>
                    {% endfor %}
                </ol>
                <div class="carousel-inner">
                    {% for image in ad.images %}
                        <div class="carousel-item {% if loop.first %} active {% endif %}">
                        <img src="{{ image.url }}" class="d-block w-100" alt="slide">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>{{ ad.title }}</h5>
                                <p>{{  image.caption }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <hr>

            {% if ad.comments|length > 0 %}
                <h2 class="mb-3">Commentaires de nos clients :</h2>

                <div class="alert alert-info">
                    <h4 class="alert-heading text-center">
                        <div class="row align-items-center">
                            <div class="col">
                                Note globale donnée par nos clients
                            </div>
                            <div class="col">
                                {% include 'presta/partials/rating.html.twig' with {'rating': ad.avgRatings} %}
                                <br>
                                <small>(Calculée sur {{ ad.comments|length }} avis)</small>
                            </div>
                        </div>
                    </h4>
                </div>

                {% for comment in ad.comments %}
                    <div class="bg-light rounded mb-3 py-3 px-3">
                        <strong>{{ comment.author.firstName }}</strong> a dit :
                        <blockquote>
                            {{comment.content}}
                        </blockquote>
                        <strong>Note donnée : </strong>
 
                        {% include 'partials/rating.html.twig' with {'rating': comment.rating} %}
                    </div>
                {% endfor %}
            {% else %}
                <h2>Cette prestation n'a pas encore reçu de commentaires ...</h2>
            {% endif %}
        </div>
        <div class="col">
        {% set a = ad.author  %}
            <div class="row">
                <div class="col-3">
                    <a href="{{ path('presta_user_show', {'slug': a.slug}) }}">
                        <img src="{{   a.picture }}" class="avatar avatar-medium" alt="Avatar de  {{   a.fullName  }}">
                    </a>
                </div>
                <div class="col">
                    <a href="{{ path('presta_user_show', {'slug': a.slug}) }}">
                        <h3>  {{   a.fullName  }}</h3>
                    </a>
                    <span class="badge badge-primary"> {{   a.ads | length  }} prestations</span>
                </div>
            </div>
            {{  a.description | raw }}
        </div>
    </div>
</div>

{% endblock %}

{% block javascripts %}

<script src="{{ asset('build/js/contact.js') }}"></script>

{% endblock %}